blank_issues_enabled: false
issue_templates:
  - name: ğŸ Bug Report
    description: ë²„ê·¸ë¥¼ ì œë³´í•˜ë ¤ë©´ ì´ í…œí”Œë¦¿ì„ ì‚¬ìš©í•˜ì„¸ìš”.
    file: bug_issue_template.md

  - name: âœ¨ Feature Request
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ì œì•ˆí•˜ë ¤ë©´ ì´ í…œí”Œë¦¿ì„ ì‚¬ìš©í•˜ì„¸ìš”.
    file: feature_issue_template.md

  - name: ğŸ”§ Refactor Task
    description: ë¦¬íŒ©í† ë§ ì‘ì—…ì„ ìœ„í•´ ì´ í…œí”Œë¦¿ì„ ì‚¬ìš©í•˜ì„¸ìš”.
    file: refactor_issue_template.md
